### ISSUE TITLE
link to releases in INSTALL.md points to adr-tools releases page

### ISSUE THREAD

**Issue by HotFusionMan** [npryce/pottery#5]
The "releases page" link in the "From a Release Package" section of INSTALL.md points to 
https://github.com/npryce/adr-tools/releases, probably a simple copy-paste error from that project's INSTALL.md file.

**Comment by npryce** [comment]
Oops. That’s the problem with the approach outlined in ADR 2.

**Comment by npryce** [comment]
Fixed
